---
- hosts: subscribie
  remote_user: root
  vars:
    domain: subscribie.co.uk

  tasks:

    - name: Set hostname subscribie.co.uk
      hostname:
        name: subscribie.co.uk

    - name: Install apache2
      apt:
        name: apache2
        state: present
        force_apt_get: yes

    - name: a2enmod rewrite
      apache2_module: name=rewrite state=present

    - name: a2enmod proxy
      apache2_module: name=proxy state=present

    - name: a2enmod proxy_uwsgi
      apache2_module: name=proxy_uwsgi state=present

    - name: Install python3, pip3, libpcre3, libpcre3-dev, libapache2-mod-proxy-uwsgi
      apt:
        pkg:
          - python3.6
          - python3-pip
          - libpcre3 
          - libpcre3-dev
          - libapache2-mod-proxy-uwsgi
        force_apt_get: yes

    - name: Install uwsgi
      pip:
        name: uwsgi==2.0.18

    - name: Install systemd service for uwsgi
      template:
        src: templates/systemd/uwsgi.service.j2
        dest: /etc/systemd/system/uwsgi.service

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Add user subwebbuild
      user:
        name: subwebbuild
        shell: /bin/bash

    - name: Template website { domain }.conf
      template:
        src: templates/apache2/domain.conf.j2
        dest: /etc/apache2/sites-available/{{ domain }}.conf

    - name: Create directory for vassals
      file:
        path: /home/subwebbuild/www/vassals
        state: directory
        owner: subwebbuild
        group: subwebbuild

    - name: Copy over config.ini
      template: 
        src: templates/uwsgi/config.ini
        dest: /home/subwebbuild/www
        owner: subwebbuild
        group: subwebbuild

    ## Create subscribie.co.uk vassal
    - name: Create subscribie.co.uk vassal
      file:
        path: /home/subwebbuild/www/vassals/{{ domain }}
        state: directory
        owner: subwebbuild
        group: subwebbuild

    - name: Clone subscribie for {{ domain }} vassal
      git:
        repo: https://github.com/Subscribie/subscribie.git 
        dest: /home/subwebbuild/www/vassals/{{ domain }}

    - name: Place vassal ini config for {{ domain }}
      template:
        src: templates/uwsgi/vassal.ini.j2
        dest: /home/subwebbuild/www/vassals/{{ domain }}/{{ domain }}.ini

    - name: Create virtualenv for vassel {{ domain }}
      pip:
        virtualenv: /home/subwebbuild/www/vassals/{{ domain }}/venv
        virtualenv_python: python3
        requirements: /home/subwebbuild/www/vassals/{{ domain }}/requirements.txt

    - name: Init vassal site using subscribie init for {{ domain }}
      command: /home/subwebbuild/www/vassals/{{ domain }}/venv/bin/subscribie init   
      args:
        chdir: /home/subwebbuild/www/vassals/{{ domain }}
        creates: /home/subwebbuild/www/vassals/{{ domain }}/jamla.yaml


    - name: Change ownership of vassals to subwebbuild
      file: 
        path: /home/subwebbuild/www/vassals/
        state: directory
        recurse: Yes
        owner: subwebbuild
        group: subwebbuild

    - name: Start uwsgi service
      service:
        name: uwsgi
        state: restarted

    - name: Restart apache2
      service:
        name: apache2
        state: restarted


